/**
 * Projects data - All portfolio projects
 */

import { Project, ProjectType } from '../types/index';

export const projects: Project[] = [
  {
    id: 'project-1',
    title: 'Miku Fan',
    year: 2026,
    softwareUsed: ['React', 'TypeScript', 'Tailwind CSS'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-2',
    title: 'Unity Character',
    year: 2026,
    softwareUsed: ['Unity', 'C#', 'Blender'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-3',
    title: 'Care Cycle',
    year: 2026,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Group,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-4',
    title: 'Sage',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-5',
    title: 'Viper',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-6',
    title: 'Sky',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-7',
    title: 'Zehara',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-8',
    title: 'Alyssa',
    year: 2020,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-9',
    title: 'Clair (First Character)',
    year: 2018,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-10',
    title: 'Homo Sapian',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-11',
    title: 'Nature',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-12',
    title: 'Space',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-13',
    title: 'Mars',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-14',
    title: 'Murasaki',
    year: 2020,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-15',
    title: 'Hogwarts Express Restoration',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-16',
    title: 'Donutsu',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-17',
    title: 'Capsules',
    year: 2022,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-18',
    title: 'Chucky But Cute',
    year: 2021,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-19',
    title: "Thor's Mjolnir",
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-20',
    title: 'Pendulum',
    year: 2022,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-21',
    title: 'Destruction',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-22',
    title: 'Abstract',
    year: 2020,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-23',
    title: 'Trophy',
    year: 2019,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
  {
    id: 'project-24',
    title: 'Bedroom',
    year: 2018,
    softwareUsed: ['Your Tech Stack'],
    projectType: ProjectType.Individual,
    images: [],
    videoUrl: '',
  },
];
